# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#trigger:
#  branches:
#    include: [ main, develop, release/* ]
#  tags:
#    include: [ 'v*' ]
#pr: none

pool: 
  name: home-office
  #vmImage: ubuntu-latest

steps:
- checkout: self
  fetchDepth: 0

- powershell: |
    $ErrorActionPreference = 'Stop'
    git config user.name  "ci-mirror"
    git config user.email "ci-mirror@example.com"

    # Construye Authorization: Basic <base64(user:token)> sin exponer el PAT
    $pair = "$(GITHUB_USER):$(GITHUB_PAT)"
    $bytes = [System.Text.Encoding]::ASCII.GetBytes($pair)
    $b64  = [System.Convert]::ToBase64String($bytes)

    $url  = "https://github.com/DalizC/barriolink-frontend.git"

    # Espejo no destructivo: crea/actualiza ramas y tags
    # 1) Trae TODAS las ramas y tags desde Azure (origin)
    git fetch --prune --tags origin +refs/heads/*:refs/remotes/origin/*
    # 2) Push TODAS las ramas remotas de origin a heads de GitHub
    git -c http.extraheader="Authorization: Basic $b64" push $url --prune refs/remotes/origin/*:refs/heads/*
    # 3) Push tags
    git -c http.extraheader="Authorization: Basic $b64" push $url --tags
  displayName: 'Mirror ALL branches & tags to GitHub'
