# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include: [ main, develop, release/* ]

pool: 
  name: home-office

steps:
  - checkout: self
    fetchDepth: 0

  - script: |
      set -e
      git config user.name "Azure DevOps"
      git config user.email "build@azuredevops.local"

      git remote remove github || true

      git remote add github https://$(GITHUB_USER):$(GITHUB_PAT)@github.com/$(GITHUB_OWNER)/$(GITHUB_REPO).git

      BRANCH="$(Build.SourceBranchName)"
      echo "Pushing branch $BRANCH to $(GITHUB_REPO)..."
      git push github "HEAD:refs/heads/$BRANCH" --force-with-lease

    displayName: 'Mirror to GitHub'