import { Component } from '@angular/core';
import { IRecentOrders } from '../../../shared/interface/events/events';
import { ITableConfigs } from '../../../shared/interface/common';
import { DataTable } from '../../../shared/components/ui/datatable/datatable';

@Component({
  selector: 'app-events-admin',
  imports: [DataTable],
  templateUrl: './events-admin.html',
  styleUrl: './events-admin.scss'
})
export class EventsAdmin {
  public tableConfig: ITableConfigs<IRecentOrders> = {
    columns: [
      { title: 'Product Name', field_value: 'product_name', sort: true },
      { title: 'Customers', field_value: 'customer_name', sort: true },
      { title: 'Qty', field_value: 'quantity', sort: true, type: 'qty' },
      {
        title: 'Total Price',
        field_value: 'total_price',
        sort: true,
        type: 'price',
      },
      { title: 'Order Date', field_value: 'order_date', sort: true },
      { title: 'Status', field_value: 'status', sort: true },
    ],
    data: [
      {
        id: 1,
        product_name: 'Festival de Verano 2025',
        product_image: 'assets/images/events/event1.jpg',
        product_id: 'EVT001',
        customer_name: 'María González',
        quantity: 45,
        total_price: '2250',
        order_date: '2025-01-15',
        status: '<span class="badge badge-light-success">Confirmado</span>',
        status_color: 'success',
        category: 'Festival',
      },
      {
        id: 2,
        product_name: 'Taller de Cocina',
        product_image: 'assets/images/events/event2.jpg',
        product_id: 'EVT002',
        customer_name: 'Juan Pérez',
        quantity: 20,
        total_price: '800',
        order_date: '2025-01-18',
        status: '<span class="badge badge-light-warning">Pendiente</span>',
        status_color: 'warning',
        category: 'Taller',
      },
      {
        id: 3,
        product_name: 'Concierto de Jazz',
        product_image: 'assets/images/events/event3.jpg',
        product_id: 'EVT003',
        customer_name: 'Ana Martínez',
        quantity: 150,
        total_price: '9000',
        order_date: '2025-01-20',
        status: '<span class="badge badge-light-success">Confirmado</span>',
        status_color: 'success',
        category: 'Concierto',
      },
      {
        id: 4,
        product_name: 'Clase de Yoga',
        product_image: 'assets/images/events/event4.jpg',
        product_id: 'EVT004',
        customer_name: 'Carlos Rodríguez',
        quantity: 30,
        total_price: '900',
        order_date: '2025-01-22',
        status: '<span class="badge badge-light-danger">Cancelado</span>',
        status_color: 'danger',
        category: 'Deportivo',
      },
      {
        id: 5,
        product_name: 'Feria Gastronómica',
        product_image: 'assets/images/events/event5.jpg',
        product_id: 'EVT005',
        customer_name: 'Laura Fernández',
        quantity: 200,
        total_price: '8000',
        order_date: '2025-01-25',
        status: '<span class="badge badge-light-success">Confirmado</span>',
        status_color: 'success',
        category: 'Feria',
      },
      {
        id: 6,
        product_name: 'Torneo de Ajedrez',
        product_image: 'assets/images/events/event6.jpg',
        product_id: 'EVT006',
        customer_name: 'Pedro Sánchez',
        quantity: 32,
        total_price: '640',
        order_date: '2025-02-01',
        status: '<span class="badge badge-light-warning">Pendiente</span>',
        status_color: 'warning',
        category: 'Deportivo',
      },
      {
        id: 7,
        product_name: 'Cine al Aire Libre',
        product_image: 'assets/images/events/event7.jpg',
        product_id: 'EVT007',
        customer_name: 'Sofía López',
        quantity: 100,
        total_price: '3000',
        order_date: '2025-02-05',
        status: '<span class="badge badge-light-success">Confirmado</span>',
        status_color: 'success',
        category: 'Cultural',
      },
      {
        id: 8,
        product_name: 'Maratón Comunitaria',
        product_image: 'assets/images/events/event8.jpg',
        product_id: 'EVT008',
        customer_name: 'Diego Torres',
        quantity: 250,
        total_price: '12500',
        order_date: '2025-02-10',
        status: '<span class="badge badge-light-success">Confirmado</span>',
        status_color: 'success',
        category: 'Deportivo',
      },
      {
        id: 9,
        product_name: 'Exposición de Arte',
        product_image: 'assets/images/events/event9.jpg',
        product_id: 'EVT009',
        customer_name: 'Carmen Ruiz',
        quantity: 75,
        total_price: '3750',
        order_date: '2025-02-12',
        status: '<span class="badge badge-light-warning">Pendiente</span>',
        status_color: 'warning',
        category: 'Cultural',
      },
      {
        id: 10,
        product_name: 'Carnaval Barrial',
        product_image: 'assets/images/events/event10.jpg',
        product_id: 'EVT010',
        customer_name: 'Roberto Díaz',
        quantity: 300,
        total_price: '15000',
        order_date: '2025-02-15',
        status: '<span class="badge badge-light-success">Confirmado</span>',
        status_color: 'success',
        category: 'Festival',
      },
      {
        id: 11,
        product_name: 'Taller de Fotografía',
        product_image: 'assets/images/events/event11.jpg',
        product_id: 'EVT011',
        customer_name: 'Isabel Moreno',
        quantity: 15,
        total_price: '900',
        order_date: '2025-02-18',
        status: '<span class="badge badge-light-danger">Cancelado</span>',
        status_color: 'danger',
        category: 'Taller',
      },
      {
        id: 12,
        product_name: 'Noche de Karaoke',
        product_image: 'assets/images/events/event12.jpg',
        product_id: 'EVT012',
        customer_name: 'Francisco Castro',
        quantity: 60,
        total_price: '1800',
        order_date: '2025-02-20',
        status: '<span class="badge badge-light-success">Confirmado</span>',
        status_color: 'success',
        category: 'Recreativo',
      },
    ] as IRecentOrders[],
  };
}
